// 国家和地区数据（所有地名必须用汉语！）

const LocationData = {
    // 国家数据：包含国名和国旗emoji
    countries: [
        { code: 'RC', name: '田国（琳凯蒂亚）', flag: '<img src="rincatian-flag.png" alt="琳凯蒂亚国旗" class="flag-icon" style="width: 28px; height: 20px; vertical-align: middle;" />' },
        { code: 'CN', name: '中国', flag: '🇨🇳' },
        { code: 'US', name: '美国', flag: '🇺🇸' },
        { code: 'JP', name: '日本', flag: '🇯🇵' },
        { code: 'KR', name: '韩国', flag: '🇰🇷' },
        { code: 'GB', name: '英国', flag: '🇬🇧' },
        { code: 'FR', name: '法国', flag: '🇫🇷' },
        { code: 'DE', name: '德国', flag: '🇩🇪' },
        { code: 'CA', name: '加拿大', flag: '🇨🇦' },
        { code: 'AU', name: '澳大利亚', flag: '🇦🇺' },
        { code: 'RU', name: '俄罗斯', flag: '🇷🇺' },
        { code: 'IN', name: '印度', flag: '🇮🇳' },
        { code: 'BR', name: '巴西', flag: '🇧🇷' },
        { code: 'IT', name: '意大利', flag: '🇮🇹' },
        { code: 'ES', name: '西班牙', flag: '🇪🇸' },
        { code: 'MX', name: '墨西哥', flag: '🇲🇽' },
        { code: 'ID', name: '印度尼西亚', flag: '🇮🇩' },
        { code: 'NL', name: '荷兰', flag: '🇳🇱' },
        { code: 'SA', name: '沙特阿拉伯', flag: '🇸🇦' },
        { code: 'TR', name: '土耳其', flag: '🇹🇷' },
        { code: 'CH', name: '瑞士', flag: '🇨🇭' },
        { code: 'SE', name: '瑞典', flag: '🇸🇪' },
        { code: 'NO', name: '挪威', flag: '🇳🇴' },
        { code: 'DK', name: '丹麦', flag: '🇩🇰' },
        { code: 'SG', name: '新加坡', flag: '🇸🇬' },
        { code: 'MY', name: '马来西亚', flag: '🇲🇾' },
        { code: 'TH', name: '泰国', flag: '🇹🇭' },
        { code: 'VN', name: '越南', flag: '🇻🇳' },
        { code: 'PH', name: '菲律宾', flag: '🇵🇭' },
        { code: 'ZA', name: '南非', flag: '🇿🇦' },
        { code: 'EG', name: '埃及', flag: '🇪🇬' },
        { code: 'AR', name: '阿根廷', flag: '🇦🇷' },
        { code: 'CL', name: '智利', flag: '🇨🇱' },
        { code: 'PL', name: '波兰', flag: '🇵🇱' },
        { code: 'BE', name: '比利时', flag: '🇧🇪' },
        { code: 'AT', name: '奥地利', flag: '🇦🇹' },
        { code: 'IE', name: '爱尔兰', flag: '🇮🇪' },
        { code: 'IL', name: '以色列', flag: '🇮🇱' },
        { code: 'NZ', name: '新西兰', flag: '🇳🇿' },
        { code: 'PT', name: '葡萄牙', flag: '🇵🇹' },
        { code: 'GR', name: '希腊', flag: '🇬🇷' },
        { code: 'CZ', name: '捷克', flag: '🇨🇿' },
        { code: 'HU', name: '匈牙利', flag: '🇭🇺' },
        { code: 'FI', name: '芬兰', flag: '🇫🇮' },
        { code: 'UA', name: '乌克兰', flag: '🇺🇦' },
        { code: 'RO', name: '罗马尼亚', flag: '🇷🇴' },
        { code: 'BG', name: '保加利亚', flag: '🇧🇬' },
        { code: 'HR', name: '克罗地亚', flag: '🇭🇷' },
        { code: 'RS', name: '塞尔维亚', flag: '🇷🇸' },
        { code: 'SK', name: '斯洛伐克', flag: '🇸🇰' },
        { code: 'SI', name: '斯洛文尼亚', flag: '🇸🇮' }
    ],
    
    // 中国省市县数据
    china: {
        provinces: [
            { code: 'BJ', name: '北京市' },
            { code: 'SH', name: '上海市' },
            { code: 'TJ', name: '天津市' },
            { code: 'CQ', name: '重庆市' },
            { code: 'HE', name: '河北省' },
            { code: 'SX', name: '山西省' },
            { code: 'NM', name: '内蒙古自治区' },
            { code: 'LN', name: '辽宁省' },
            { code: 'JL', name: '吉林省' },
            { code: 'HL', name: '黑龙江省' },
            { code: 'JS', name: '江苏省' },
            { code: 'ZJ', name: '浙江省' }, 
            { code: 'AH', name: '安徽省' },
            { code: 'FJ', name: '福建省' },
            { code: 'JX', name: '江西省' },
            { code: 'SD', name: '山东省' },
            { code: 'HA', name: '河南省' },
            { code: 'HB', name: '湖北省' },
            { code: 'HN', name: '湖南省' },
            { code: 'GD', name: '广东省' },
            { code: 'GX', name: '广西壮族自治区' },
            { code: 'HI', name: '海南省' },
            { code: 'SC', name: '四川省' },
            { code: 'GZ', name: '贵州省' },
            { code: 'YN', name: '云南省' },
            { code: 'XZ', name: '西藏自治区' },
            { code: 'SN', name: '陕西省' },
            { code: 'GS', name: '甘肃省' },
            { code: 'QH', name: '青海省' },
            { code: 'NX', name: '宁夏回族自治区' },
            { code: 'XJ', name: '新疆维吾尔自治区' },
            { code: 'TW', name: '台湾省' },
            { code: 'HK', name: '香港特别行政区' },
            { code: 'MO', name: '澳门特别行政区' }
        ],
        cities: {
            'BJ': [
                { code: 'BJ-1', name: '东城区' },
                { code: 'BJ-2', name: '西城区' },
                { code: 'BJ-3', name: '朝阳区' },
                { code: 'BJ-4', name: '丰台区' },
                { code: 'BJ-5', name: '石景山区' },
                { code: 'BJ-6', name: '海淀区' },
                { code: 'BJ-7', name: '门头沟区' },
                { code: 'BJ-8', name: '房山区' },
                { code: 'BJ-9', name: '通州区' },
                { code: 'BJ-10', name: '顺义区' },
                { code: 'BJ-11', name: '昌平区' },
                { code: 'BJ-12', name: '大兴区' },
                { code: 'BJ-13', name: '怀柔区' },
                { code: 'BJ-14', name: '平谷区' },
                { code: 'BJ-15', name: '密云区' },
                { code: 'BJ-16', name: '延庆区' }
            ],
            'SH': [
                { code: 'SH-1', name: '黄浦区' },
                { code: 'SH-2', name: '徐汇区' },
                { code: 'SH-3', name: '长宁区' },
                { code: 'SH-4', name: '静安区' },
                { code: 'SH-5', name: '普陀区' },
                { code: 'SH-6', name: '虹口区' },
                { code: 'SH-7', name: '杨浦区' },
                { code: 'SH-8', name: '闵行区' },
                { code: 'SH-9', name: '宝山区' },
                { code: 'SH-10', name: '嘉定区' },
                { code: 'SH-11', name: '浦东新区' },
                { code: 'SH-12', name: '金山区' },
                { code: 'SH-13', name: '松江区' },
                { code: 'SH-14', name: '青浦区' },
                { code: 'SH-15', name: '奉贤区' },
                { code: 'SH-16', name: '崇明区' }
            ],
            'TJ': [
                { code: 'TJ-1', name: '和平区' },
                { code: 'TJ-2', name: '河东区' },
                { code: 'TJ-3', name: '河西区' },
                { code: 'TJ-4', name: '南开区' },
                { code: 'TJ-5', name: '河北区' },
                { code: 'TJ-6', name: '红桥区' },
                { code: 'TJ-7', name: '东丽区' },
                { code: 'TJ-8', name: '西青区' },
                { code: 'TJ-9', name: '津南区' },
                { code: 'TJ-10', name: '北辰区' },
                { code: 'TJ-11', name: '武清区' },
                { code: 'TJ-12', name: '宝坻区' },
                { code: 'TJ-13', name: '滨海新区' },
                { code: 'TJ-14', name: '宁河区' },
                { code: 'TJ-15', name: '静海区' },
                { code: 'TJ-16', name: '蓟州区' }
            ],
            'CQ': [
                { code: 'CQ-1', name: '万州区' },
                { code: 'CQ-2', name: '涪陵区' },
                { code: 'CQ-3', name: '渝中区' },
                { code: 'CQ-4', name: '大渡口区' },
                { code: 'CQ-5', name: '江北区' },
                { code: 'CQ-6', name: '沙坪坝区' },
                { code: 'CQ-7', name: '九龙坡区' },
                { code: 'CQ-8', name: '南岸区' },
                { code: 'CQ-9', name: '北碚区' },
                { code: 'CQ-10', name: '綦江区' },
                { code: 'CQ-11', name: '大足区' },
                { code: 'CQ-12', name: '渝北区' },
                { code: 'CQ-13', name: '巴南区' },
                { code: 'CQ-14', name: '黔江区' },
                { code: 'CQ-15', name: '长寿区' },
                { code: 'CQ-16', name: '江津区' },
                { code: 'CQ-17', name: '合川区' },
                { code: 'CQ-18', name: '永川区' },
                { code: 'CQ-19', name: '南川区' },
                { code: 'CQ-20', name: '璧山区' },
                { code: 'CQ-21', name: '铜梁区' },
                { code: 'CQ-22', name: '潼南区' },
                { code: 'CQ-23', name: '荣昌区' },
                { code: 'CQ-24', name: '开州区' },
                { code: 'CQ-25', name: '梁平区' },
                { code: 'CQ-26', name: '武隆区' },
                { code: 'CQ-27', name: '城口县' },
                { code: 'CQ-28', name: '丰都县' },
                { code: 'CQ-29', name: '垫江县' },
                { code: 'CQ-30', name: '忠县' },
                { code: 'CQ-31', name: '云阳县' },
                { code: 'CQ-32', name: '奉节县' },
                { code: 'CQ-33', name: '巫山县' },
                { code: 'CQ-34', name: '巫溪县' },
                { code: 'CQ-35', name: '石柱土家族自治县' },
                { code: 'CQ-36', name: '秀山土家族苗族自治县' },
                { code: 'CQ-37', name: '酉阳土家族苗族自治县' },
                { code: 'CQ-38', name: '彭水苗族土家族自治县' }
            ],
            'HE': [
                { code: 'HE-1', name: '石家庄市' },
                { code: 'HE-2', name: '唐山市' },
                { code: 'HE-3', name: '秦皇岛市' },
                { code: 'HE-4', name: '邯郸市' },
                { code: 'HE-5', name: '邢台市' },
                { code: 'HE-6', name: '保定市' },
                { code: 'HE-7', name: '张家口市' },
                { code: 'HE-8', name: '承德市' },
                { code: 'HE-9', name: '沧州市' },
                { code: 'HE-10', name: '廊坊市' },
                { code: 'HE-11', name: '衡水市' }
            ],
            'SX': [
                { code: 'SX-1', name: '太原市' },
                { code: 'SX-2', name: '大同市' },
                { code: 'SX-3', name: '阳泉市' },
                { code: 'SX-4', name: '长治市' },
                { code: 'SX-5', name: '晋城市' },
                { code: 'SX-6', name: '朔州市' },
                { code: 'SX-7', name: '晋中市' },
                { code: 'SX-8', name: '运城市' },
                { code: 'SX-9', name: '忻州市' },
                { code: 'SX-10', name: '临汾市' },
                { code: 'SX-11', name: '吕梁市' }
            ],
            'NM': [
                { code: 'NM-1', name: '呼和浩特市' },
                { code: 'NM-2', name: '包头市' },
                { code: 'NM-3', name: '乌海市' },
                { code: 'NM-4', name: '赤峰市' },
                { code: 'NM-5', name: '通辽市' },
                { code: 'NM-6', name: '鄂尔多斯市' },
                { code: 'NM-7', name: '呼伦贝尔市' },
                { code: 'NM-8', name: '巴彦淖尔市' },
                { code: 'NM-9', name: '乌兰察布市' },
                { code: 'NM-10', name: '兴安盟' },
                { code: 'NM-11', name: '锡林郭勒盟' },
                { code: 'NM-12', name: '阿拉善盟' }
            ],
            'LN': [
                { code: 'LN-1', name: '沈阳市' },
                { code: 'LN-2', name: '大连市' },
                { code: 'LN-3', name: '鞍山市' },
                { code: 'LN-4', name: '抚顺市' },
                { code: 'LN-5', name: '本溪市' },
                { code: 'LN-6', name: '丹东市' },
                { code: 'LN-7', name: '锦州市' },
                { code: 'LN-8', name: '营口市' },
                { code: 'LN-9', name: '阜新市' },
                { code: 'LN-10', name: '辽阳市' },
                { code: 'LN-11', name: '盘锦市' },
                { code: 'LN-12', name: '铁岭市' },
                { code: 'LN-13', name: '朝阳市' },
                { code: 'LN-14', name: '葫芦岛市' }
            ],
            'JL': [
                { code: 'JL-1', name: '长春市' },
                { code: 'JL-2', name: '吉林市' },
                { code: 'JL-3', name: '四平市' },
                { code: 'JL-4', name: '辽源市' },
                { code: 'JL-5', name: '通化市' },
                { code: 'JL-6', name: '白山市' },
                { code: 'JL-7', name: '松原市' },
                { code: 'JL-8', name: '白城市' },
                { code: 'JL-9', name: '延边朝鲜族自治州' }
            ],
            'HL': [
                { code: 'HL-1', name: '哈尔滨市' },
                { code: 'HL-2', name: '齐齐哈尔市' },
                { code: 'HL-3', name: '鸡西市' },
                { code: 'HL-4', name: '鹤岗市' },
                { code: 'HL-5', name: '双鸭山市' },
                { code: 'HL-6', name: '大庆市' },
                { code: 'HL-7', name: '伊春市' },
                { code: 'HL-8', name: '佳木斯市' },
                { code: 'HL-9', name: '七台河市' },
                { code: 'HL-10', name: '牡丹江市' },
                { code: 'HL-11', name: '黑河市' },
                { code: 'HL-12', name: '绥化市' },
                { code: 'HL-13', name: '大兴安岭地区' }
            ],
            'JS': [
                { code: 'JS-1', name: '南京市' },
                { code: 'JS-2', name: '无锡市' },
                { code: 'JS-3', name: '徐州市' },
                { code: 'JS-4', name: '常州市' },
                { code: 'JS-5', name: '苏州市' },
                { code: 'JS-6', name: '南通市' },
                { code: 'JS-7', name: '连云港市' },
                { code: 'JS-8', name: '淮安市' },
                { code: 'JS-9', name: '盐城市' },
                { code: 'JS-10', name: '扬州市' },
                { code: 'JS-11', name: '镇江市' },
                { code: 'JS-12', name: '泰州市' },
                { code: 'JS-13', name: '宿迁市' }
            ],
            'ZJ': [
                { code: 'ZJ-1', name: '杭州市' },
                { code: 'ZJ-2', name: '宁波市' },
                { code: 'ZJ-3', name: '温州市' },
                { code: 'ZJ-4', name: '嘉兴市' },
                { code: 'ZJ-5', name: '湖州市' },
                { code: 'ZJ-6', name: '绍兴市' },
                { code: 'ZJ-7', name: '金华市' },
                { code: 'ZJ-8', name: '衢州市' },
                { code: 'ZJ-9', name: '舟山市' },
                { code: 'ZJ-10', name: '台州市' },
                { code: 'ZJ-11', name: '丽水市' }
            ],
            'AH': [
                { code: 'AH-1-1', name: '合肥市-瑶海区' },
                { code: 'AH-1-2', name: '合肥市-庐阳区' },
                { code: 'AH-1-3', name: '合肥市-蜀山区' },
                { code: 'AH-1-4', name: '合肥市-包河区' },
                { code: 'AH-1-5', name: '合肥市-兴湖区' },
                { code: 'AH-1-6', name: '合肥市-肥东县' },
                { code: 'AH-1-7', name: '合肥市-肥西县' },
                { code: 'AH-1-8', name: '合肥市-长丰县' },
                { code: 'AH-1-9', name: '合肥市-庐江县' },
                { code: 'AH-1-10', name: '合肥市-巢湖市' },
                { code: 'AH-2-1', name: '芜湖市-镜湖区' },
                { code: 'AH-2-2', name: '芜湖市-弋江区' },
                { code: 'AH-2-3', name: '芜湖市-鸠江区' },
                { code: 'AH-2-5', name: '芜湖市-湾沚区' },
                { code: 'AH-2-6', name: '芜湖市-繁昌区' },
                { code: 'AH-2-7', name: '芜湖市-南陵县' },
                { code: 'AH-2-8', name: '芜湖市-无为市' },
                { code: 'AH-3-1', name: '蚌埠市-龙子湖区' },
                { code: 'AH-3-2', name: '蚌埠市-蚌山区' },
                { code: 'AH-3-3', name: '蚌埠市-禹会区' },
                { code: 'AH-3-4', name: '蚌埠市-淮上区' },
                { code: 'AH-3-5', name: '蚌埠市-怀远县' },
                { code: 'AH-3-6', name: '蚌埠市-五河县' },
                { code: 'AH-3-7', name: '蚌埠市-固镇县' },
                { code: 'AH-4-1', name: '淮南市-大通区' },
                { code: 'AH-4-2', name: '淮南市-田家庵区' },
                { code: 'AH-4-3', name: '淮南市-谢家集区' },
                { code: 'AH-4-4', name: '淮南市-八公山区' },
                { code: 'AH-4-5', name: '淮南市-潘集区' },
                { code: 'AH-4-6', name: '淮南市-凤台县' },
                { code: 'AH-4-7', name: '淮南市-寿县' },
                { code: 'AH-5-1', name: '马鞍山市-花山区' },
                { code: 'AH-5-2', name: '马鞍山市-雨山区' },
                { code: 'AH-5-3', name: '马鞍山市-博望区' },
                { code: 'AH-5-4', name: '马鞍山市-当涂县' },
                { code: 'AH-5-5', name: '马鞍山市-含山县' },
                { code: 'AH-5-6', name: '马鞍山市-和县' },
                { code: 'AH-6-1', name: '淮北市-杜集区' },
                { code: 'AH-6-2', name: '淮北市-相山区' },
                { code: 'AH-6-3', name: '淮北市-烈山区' },
                { code: 'AH-6-4', name: '淮北市-濉溪县' },
                { code: 'AH-7-1', name: '铜陵市-铜官区' },
                { code: 'AH-7-2', name: '铜陵市-义安区' },
                { code: 'AH-7-3', name: '铜陵市-郊区' },
                { code: 'AH-7-4', name: '铜陵市-枞阳县' },
                { code: 'AH-8-1', name: '安庆市-迎江区' },
                { code: 'AH-8-2', name: '安庆市-大观区' },
                { code: 'AH-8-3', name: '安庆市-宜秀区' },
                { code: 'AH-8-4', name: '安庆市-怀宁县' },
                { code: 'AH-8-5', name: '安庆市-潜山市' },
                { code: 'AH-8-6', name: '安庆市-太湖县' },
                { code: 'AH-8-7', name: '安庆市-宿松县' },
                { code: 'AH-8-8', name: '安庆市-望江县' },
                { code: 'AH-8-9', name: '安庆市-岳西县' },
                { code: 'AH-8-10', name: '安庆市-桐城市' },
                { code: 'AH-9-1', name: '黄山市-屯溪区' },
                { code: 'AH-9-2', name: '黄山市-黄山区' },
                { code: 'AH-9-3', name: '黄山市-徽州区' },
                { code: 'AH-9-4', name: '黄山市-歙县' },
                { code: 'AH-9-5', name: '黄山市-休宁县' },
                { code: 'AH-9-6', name: '黄山市-黟县' },
                { code: 'AH-9-7', name: '黄山市-祁门县' },
                { code: 'AH-10-1', name: '滁州市-琅琊区' },
                { code: 'AH-10-2', name: '滁州市-南谯区' },
                { code: 'AH-10-3', name: '滁州市-来安县' },
                { code: 'AH-10-4', name: '滁州市-全椒县' },
                { code: 'AH-10-5', name: '滁州市-定远县' },
                { code: 'AH-10-6', name: '滁州市-凤阳县' },
                { code: 'AH-10-7', name: '滁州市-天长市' },
                { code: 'AH-10-8', name: '滁州市-明光市' },
                { code: 'AH-11-1', name: '阜阳市-颍州区' },
                { code: 'AH-11-2', name: '阜阳市-颍东区' },
                { code: 'AH-11-3', name: '阜阳市-颍泉区' },
                { code: 'AH-11-4', name: '阜阳市-临泉县' },
                { code: 'AH-11-5', name: '阜阳市-太和县' },
                { code: 'AH-11-6', name: '阜阳市-阜南县' },
                { code: 'AH-11-7', name: '阜阳市-颍上县' },
                { code: 'AH-11-8', name: '阜阳市-界首市' },
                { code: 'AH-12-1', name: '宿州市-埇桥区' },
                { code: 'AH-12-2', name: '宿州市-砀山县' },
                { code: 'AH-12-3', name: '宿州市-萧县' },
                { code: 'AH-12-4', name: '宿州市-灵璧县' },
                { code: 'AH-12-5', name: '宿州市-泗县' },
                { code: 'AH-13-1', name: '六安市-金安区' },
                { code: 'AH-13-2', name: '六安市-裕安区' },
                { code: 'AH-13-3', name: '六安市-叶集区' },
                { code: 'AH-13-4', name: '六安市-霍邱县' },
                { code: 'AH-13-5', name: '六安市-舒城县' },
                { code: 'AH-13-6', name: '六安市-金寨县' },
                { code: 'AH-13-7', name: '六安市-霍山县' },
                { code: 'AH-14-1', name: '亳州市-谯城区' },
                { code: 'AH-14-2', name: '亳州市-涡阳县' },
                { code: 'AH-14-3', name: '亳州市-蒙城县' },
                { code: 'AH-14-4', name: '亳州市-利辛县' },
                { code: 'AH-15-1', name: '池州市-贵池区' },
                { code: 'AH-15-2', name: '池州市-东至县' },
                { code: 'AH-15-3', name: '池州市-石台县' },
                { code: 'AH-15-4', name: '池州市-青阳县' },
                { code: 'AH-16-1', name: '宣城市-宣州区' },
                { code: 'AH-16-2', name: '宣城市-郎溪县' },
                { code: 'AH-16-3', name: '宣城市-广德县' },
                { code: 'AH-16-4', name: '宣城市-泾县' },
                { code: 'AH-16-5', name: '宣城市-绩溪县' },
                { code: 'AH-16-6', name: '宣城市-旌德县' },
                { code: 'AH-16-7', name: '宣城市-宁国市' }
            ],
            'FJ': [
                { code: 'FJ-1', name: '福州市' },
                { code: 'FJ-2', name: '厦门市' },
                { code: 'FJ-3', name: '莆田市' },
                { code: 'FJ-4', name: '三明市' },
                { code: 'FJ-5', name: '泉州市' },
                { code: 'FJ-6', name: '漳州市' },
                { code: 'FJ-7', name: '南平市' },
                { code: 'FJ-8', name: '龙岩市' },
                { code: 'FJ-9', name: '宁德市' }
            ],
            'JX': [
                { code: 'JX-1', name: '南昌市' },
                { code: 'JX-2', name: '景德镇市' },
                { code: 'JX-3', name: '萍乡市' },
                { code: 'JX-4', name: '九江市' },
                { code: 'JX-5', name: '新余市' },
                { code: 'JX-6', name: '鹰潭市' },
                { code: 'JX-7', name: '赣州市' },
                { code: 'JX-8', name: '吉安市' },
                { code: 'JX-9', name: '宜春市' },
                { code: 'JX-10', name: '抚州市' },
                { code: 'JX-11', name: '上饶市' }
            ],
            'SD': [
                { code: 'SD-1', name: '济南市' },
                { code: 'SD-2', name: '青岛市' },
                { code: 'SD-3', name: '淄博市' },
                { code: 'SD-4', name: '枣庄市' },
                { code: 'SD-5', name: '东营市' },
                { code: 'SD-6', name: '烟台市' },
                { code: 'SD-7', name: '潍坊市' },
                { code: 'SD-8', name: '济宁市' },
                { code: 'SD-9', name: '泰安市' },
                { code: 'SD-10', name: '威海市' },
                { code: 'SD-11', name: '日照市' },
                { code: 'SD-12', name: '临沂市' },
                { code: 'SD-13', name: '德州市' },
                { code: 'SD-14', name: '聊城市' },
                { code: 'SD-15', name: '滨州市' },
                { code: 'SD-16', name: '菏泽市' }
            ],
            'HA': [
                { code: 'HA-1', name: '郑州市' },
                { code: 'HA-2', name: '开封市' },
                { code: 'HA-3', name: '洛阳市' },
                { code: 'HA-4', name: '平顶山市' },
                { code: 'HA-5', name: '安阳市' },
                { code: 'HA-6', name: '鹤壁市' },
                { code: 'HA-7', name: '新乡市' },
                { code: 'HA-8', name: '焦作市' },
                { code: 'HA-9', name: '濮阳市' },
                { code: 'HA-10', name: '许昌市' },
                { code: 'HA-11', name: '漯河市' },
                { code: 'HA-12', name: '三门峡市' },
                { code: 'HA-13', name: '南阳市' },
                { code: 'HA-14', name: '商丘市' },
                { code: 'HA-15', name: '信阳市' },
                { code: 'HA-16', name: '周口市' },
                { code: 'HA-17', name: '驻马店市' },
                { code: 'HA-18', name: '济源市' }
            ],
            'HB': [
                { code: 'HB-1', name: '武汉市' },
                { code: 'HB-2', name: '黄石市' },
                { code: 'HB-3', name: '十堰市' },
                { code: 'HB-4', name: '宜昌市' },
                { code: 'HB-5', name: '襄阳市' },
                { code: 'HB-6', name: '鄂州市' },
                { code: 'HB-7', name: '荆门市' },
                { code: 'HB-8', name: '孝感市' },
                { code: 'HB-9', name: '荆州市' },
                { code: 'HB-10', name: '黄冈市' },
                { code: 'HB-11', name: '咸宁市' },
                { code: 'HB-12', name: '随州市' },
                { code: 'HB-13', name: '恩施土家族苗族自治州' },
                { code: 'HB-14', name: '仙桃市' },
                { code: 'HB-15', name: '潜江市' },
                { code: 'HB-16', name: '天门市' },
                { code: 'HB-17', name: '神农架林区' }
            ],
            'HN': [
                { code: 'HN-1', name: '长沙市' },
                { code: 'HN-2', name: '株洲市' },
                { code: 'HN-3', name: '湘潭市' },
                { code: 'HN-4', name: '衡阳市' },
                { code: 'HN-5', name: '邵阳市' },
                { code: 'HN-6', name: '岳阳市' },
                { code: 'HN-7', name: '常德市' },
                { code: 'HN-8', name: '张家界市' },
                { code: 'HN-9', name: '益阳市' },
                { code: 'HN-10', name: '郴州市' },
                { code: 'HN-11', name: '永州市' },
                { code: 'HN-12', name: '怀化市' },
                { code: 'HN-13', name: '娄底市' },
                { code: 'HN-14', name: '湘西土家族苗族自治州' }
            ],
            'GD': [
                { code: 'GD-1', name: '广州市' },
                { code: 'GD-2', name: '深圳市' },
                { code: 'GD-3', name: '珠海市' },
                { code: 'GD-4', name: '汕头市' },
                { code: 'GD-5', name: '佛山市' },
                { code: 'GD-6', name: '韶关市' },
                { code: 'GD-7', name: '湛江市' },
                { code: 'GD-8', name: '肇庆市' },
                { code: 'GD-9', name: '江门市' },
                { code: 'GD-10', name: '茂名市' },
                { code: 'GD-11', name: '惠州市' },
                { code: 'GD-12', name: '梅州市' },
                { code: 'GD-13', name: '汕尾市' },
                { code: 'GD-14', name: '河源市' },
                { code: 'GD-15', name: '阳江市' },
                { code: 'GD-16', name: '清远市' },
                { code: 'GD-17', name: '东莞市' },
                { code: 'GD-18', name: '中山市' },
                { code: 'GD-19', name: '潮州市' },
                { code: 'GD-20', name: '揭阳市' },
                { code: 'GD-21', name: '云浮市' }
            ],
            'GX': [
                { code: 'GX-1', name: '南宁市' },
                { code: 'GX-2', name: '柳州市' },
                { code: 'GX-3', name: '桂林市' },
                { code: 'GX-4', name: '梧州市' },
                { code: 'GX-5', name: '北海市' },
                { code: 'GX-6', name: '防城港市' },
                { code: 'GX-7', name: '钦州市' },
                { code: 'GX-8', name: '贵港市' },
                { code: 'GX-9', name: '玉林市' },
                { code: 'GX-10', name: '百色市' },
                { code: 'GX-11', name: '贺州市' },
                { code: 'GX-12', name: '河池市' },
                { code: 'GX-13', name: '来宾市' },
                { code: 'GX-14', name: '崇左市' }
            ],
            'HI': [
                { code: 'HI-1', name: '海口市' },
                { code: 'HI-2', name: '三亚市' },
                { code: 'HI-3', name: '三沙市' },
                { code: 'HI-4', name: '儋州市' },
                { code: 'HI-5', name: '五指山市' },
                { code: 'HI-6', name: '琼海市' },
                { code: 'HI-7', name: '文昌市' },
                { code: 'HI-8', name: '万宁市' },
                { code: 'HI-9', name: '东方市' },
                { code: 'HI-10', name: '定安县' },
                { code: 'HI-11', name: '屯昌县' },
                { code: 'HI-12', name: '澄迈县' },
                { code: 'HI-13', name: '临高县' },
                { code: 'HI-14', name: '白沙黎族自治县' },
                { code: 'HI-15', name: '昌江黎族自治县' },
                { code: 'HI-16', name: '乐东黎族自治县' },
                { code: 'HI-17', name: '陵水黎族自治县' },
                { code: 'HI-18', name: '保亭黎族苗族自治县' },
                { code: 'HI-19', name: '琼中黎族苗族自治县' }
            ],
            'SC': [
                { code: 'SC-1', name: '成都市' },
                { code: 'SC-2', name: '自贡市' },
                { code: 'SC-3', name: '攀枝花市' },
                { code: 'SC-4', name: '泸州市' },
                { code: 'SC-5', name: '德阳市' },
                { code: 'SC-6', name: '绵阳市' },
                { code: 'SC-7', name: '广元市' },
                { code: 'SC-8', name: '遂宁市' },
                { code: 'SC-9', name: '内江市' },
                { code: 'SC-10', name: '乐山市' },
                { code: 'SC-11', name: '南充市' },
                { code: 'SC-12', name: '眉山市' },
                { code: 'SC-13', name: '宜宾市' },
                { code: 'SC-14', name: '广安市' },
                { code: 'SC-15', name: '达州市' },
                { code: 'SC-16', name: '雅安市' },
                { code: 'SC-17', name: '巴中市' },
                { code: 'SC-18', name: '资阳市' },
                { code: 'SC-19', name: '阿坝藏族羌族自治州' },
                { code: 'SC-20', name: '甘孜藏族自治州' },
                { code: 'SC-21', name: '凉山彝族自治州' }
            ],
            'GZ': [
                { code: 'GZ-1', name: '贵阳市' },
                { code: 'GZ-2', name: '六盘水市' },
                { code: 'GZ-3', name: '遵义市' },
                { code: 'GZ-4', name: '安顺市' },
                { code: 'GZ-5', name: '毕节市' },
                { code: 'GZ-6', name: '铜仁市' },
                { code: 'GZ-7', name: '黔西南布依族苗族自治州' },
                { code: 'GZ-8', name: '黔东南苗族侗族自治州' },
                { code: 'GZ-9', name: '黔南布依族苗族自治州' }
            ],
            'YN': [
                { code: 'YN-1', name: '昆明市' },
                { code: 'YN-2', name: '曲靖市' },
                { code: 'YN-3', name: '玉溪市' },
                { code: 'YN-4', name: '保山市' },
                { code: 'YN-5', name: '昭通市' },
                { code: 'YN-6', name: '丽江市' },
                { code: 'YN-7', name: '普洱市' },
                { code: 'YN-8', name: '临沧市' },
                { code: 'YN-9', name: '楚雄彝族自治州' },
                { code: 'YN-10', name: '红河哈尼族彝族自治州' },
                { code: 'YN-11', name: '文山壮族苗族自治州' },
                { code: 'YN-12', name: '西双版纳傣族自治州' },
                { code: 'YN-13', name: '大理白族自治州' },
                { code: 'YN-14', name: '德宏傣族景颇族自治州' },
                { code: 'YN-15', name: '怒江傈僳族自治州' },
                { code: 'YN-16', name: '迪庆藏族自治州' }
            ],
            'XZ': [
                { code: 'XZ-1', name: '拉萨市' },
                { code: 'XZ-2', name: '日喀则市' },
                { code: 'XZ-3', name: '昌都市' },
                { code: 'XZ-4', name: '林芝市' },
                { code: 'XZ-5', name: '山南市' },
                { code: 'XZ-6', name: '那曲市' },
                { code: 'XZ-7', name: '阿里地区' }
            ],
            'SN': [
                { code: 'SN-1', name: '西安市' },
                { code: 'SN-2', name: '铜川市' },
                { code: 'SN-3', name: '宝鸡市' },
                { code: 'SN-4', name: '咸阳市' },
                { code: 'SN-5', name: '渭南市' },
                { code: 'SN-6', name: '延安市' },
                { code: 'SN-7', name: '汉中市' },
                { code: 'SN-8', name: '榆林市' },
                { code: 'SN-9', name: '安康市' },
                { code: 'SN-10', name: '商洛市' }
            ],
            'GS': [
                { code: 'GS-1', name: '兰州市' },
                { code: 'GS-2', name: '嘉峪关市' },
                { code: 'GS-3', name: '金昌市' },
                { code: 'GS-4', name: '白银市' },
                { code: 'GS-5', name: '天水市' },
                { code: 'GS-6', name: '武威市' },
                { code: 'GS-7', name: '张掖市' },
                { code: 'GS-8', name: '平凉市' },
                { code: 'GS-9', name: '酒泉市' },
                { code: 'GS-10', name: '庆阳市' },
                { code: 'GS-11', name: '定西市' },
                { code: 'GS-12', name: '陇南市' },
                { code: 'GS-13', name: '临夏回族自治州' },
                { code: 'GS-14', name: '甘南藏族自治州' }
            ],
            'QH': [
                { code: 'QH-1', name: '西宁市' },
                { code: 'QH-2', name: '海东市' },
                { code: 'QH-3', name: '海北藏族自治州' },
                { code: 'QH-4', name: '黄南藏族自治州' },
                { code: 'QH-5', name: '海南藏族自治州' },
                { code: 'QH-6', name: '果洛藏族自治州' },
                { code: 'QH-7', name: '玉树藏族自治州' },
                { code: 'QH-8', name: '海西蒙古族藏族自治州' }
            ],
            'NX': [
                { code: 'NX-1', name: '银川市' },
                { code: 'NX-2', name: '石嘴山市' },
                { code: 'NX-3', name: '吴忠市' },
                { code: 'NX-4', name: '固原市' },
                { code: 'NX-5', name: '中卫市' }
            ],
            'XJ': [
                { code: 'XJ-1', name: '乌鲁木齐市' },
                { code: 'XJ-2', name: '克拉玛依市' },
                { code: 'XJ-3', name: '吐鲁番市' },
                { code: 'XJ-4', name: '哈密市' },
                { code: 'XJ-5', name: '昌吉回族自治州' },
                { code: 'XJ-6', name: '博尔塔拉蒙古自治州' },
                { code: 'XJ-7', name: '巴音郭楞蒙古自治州' },
                { code: 'XJ-8', name: '阿克苏地区' },
                { code: 'XJ-9', name: '克孜勒苏柯尔克孜自治州' },
                { code: 'XJ-10', name: '喀什地区' },
                { code: 'XJ-11', name: '和田地区' },
                { code: 'XJ-12', name: '伊犁哈萨克自治州' },
                { code: 'XJ-13', name: '塔城地区' },
                { code: 'XJ-14', name: '阿勒泰地区' },
                { code: 'XJ-15', name: '石河子市' },
                { code: 'XJ-16', name: '阿拉尔市' },
                { code: 'XJ-17', name: '图木舒克市' },
                { code: 'XJ-18', name: '五家渠市' },
                { code: 'XJ-19', name: '北屯市' },
                { code: 'XJ-20', name: '铁门关市' },
                { code: 'XJ-21', name: '双河市' },
                { code: 'XJ-22', name: '可克达拉市' },
                { code: 'XJ-23', name: '昆玉市' },
                { code: 'XJ-24', name: '福海市' },
                { code: 'XJ-25', name: '青河市' }
            ],
            'TW': [
                { code: 'TW-1', name: '台北市' },
                { code: 'TW-2', name: '新北市' },
                { code: 'TW-3', name: '桃园市' },
                { code: 'TW-4', name: '台中市' },
                { code: 'TW-5', name: '台南市' },
                { code: 'TW-6', name: '高雄市' },
                { code: 'TW-7', name: '基隆市' },
                { code: 'TW-8', name: '新竹市' },
                { code: 'TW-9', name: '嘉义市' },
                { code: 'TW-10', name: '新竹县' },
                { code: 'TW-11', name: '苗栗县' },
                { code: 'TW-12', name: '彰化县' },
                { code: 'TW-13', name: '南投县' },
                { code: 'TW-14', name: '云林县' },
                { code: 'TW-15', name: '嘉义县' },
                { code: 'TW-16', name: '屏东县' },
                { code: 'TW-17', name: '宜兰县' },
                { code: 'TW-18', name: '花莲县' },
                { code: 'TW-19', name: '台东县' },
                { code: 'TW-20', name: '澎湖县' },
                { code: 'TW-21', name: '金门县' },
                { code: 'TW-22', name: '连江县' }
            ],
            'HK': [
                { code: 'HK-1', name: '中西区' },
                { code: 'HK-2', name: '湾仔区' },
                { code: 'HK-3', name: '东区' },
                { code: 'HK-4', name: '南区' },
                { code: 'HK-5', name: '油尖旺区' },
                { code: 'HK-6', name: '深水埗区' },
                { code: 'HK-7', name: '九龙城区' },
                { code: 'HK-8', name: '黄大仙区' },
                { code: 'HK-9', name: '观塘区' },
                { code: 'HK-10', name: '荃湾区' },
                { code: 'HK-11', name: '屯门区' },
                { code: 'HK-12', name: '元朗区' },
                { code: 'HK-13', name: '北区' },
                { code: 'HK-14', name: '大埔区' },
                { code: 'HK-15', name: '沙田区' },
                { code: 'HK-16', name: '西贡区' },
                { code: 'HK-17', name: '离岛区' }
            ],
            'MO': [
                { code: 'MO-1', name: '花地玛堂区' },
                { code: 'MO-2', name: '花王堂区' },
                { code: 'MO-3', name: '望德堂区' },
                { code: 'MO-4', name: '大堂区' },
                { code: 'MO-5', name: '风顺堂区' },
                { code: 'MO-6', name: '嘉模堂区' },
                { code: 'MO-7', name: '路凼填海区' },
                { code: 'MO-8', name: '圣方济各堂区' }
            ]
        }
    },
    
    // 日本都道府县数据
    japan: {
        prefectures: [
            { code: 'JP-13', name: '东京都' },
            { code: 'JP-27', name: '大阪府' },
            { code: 'JP-23', name: '爱知县' },
            { code: 'JP-14', name: '神奈川县' },
            { code: 'JP-01', name: '北海道' },
            { code: 'JP-40', name: '福冈县' },
            { code: 'JP-11', name: '埼玉县' },
            { code: 'JP-12', name: '千叶县' },
            { code: 'JP-28', name: '兵库县' },
            { code: 'JP-08', name: '茨城县' },
            { code: 'JP-34', name: '广岛县' },
            { code: 'JP-26', name: '京都府' },
            { code: 'JP-38', name: '爱媛县' },
            { code: 'JP-10', name: '群马县' },
            { code: 'JP-39', name: '高知县' },
            { code: 'JP-21', name: '岐阜县' },
            { code: 'JP-22', name: '静冈县' },
            { code: 'JP-29', name: '奈良县' },
            { code: 'JP-24', name: '三重县' },
            { code: 'JP-35', name: '山口县' },
            { code: 'JP-33', name: '冈山县' },
            { code: 'JP-25', name: '滋贺县' },
            { code: 'JP-07', name: '福岛县' },
            { code: 'JP-19', name: '山梨县' },
            { code: 'JP-04', name: '宫城县' },
            { code: 'JP-36', name: '德岛县' },
            { code: 'JP-06', name: '山形县' },
            { code: 'JP-31', name: '鸟取县' },
            { code: 'JP-09', name: '栃木县' },
            { code: 'JP-44', name: '大分县' },
            { code: 'JP-46', name: '鹿儿岛县' },
            { code: 'JP-47', name: '冲绳县' },
            { code: 'JP-03', name: '岩手县' },
            { code: 'JP-20', name: '长野县' },
            { code: 'JP-15', name: '新潟县' },
            { code: 'JP-43', name: '熊本县' },
            { code: 'JP-32', name: '岛根县' },
            { code: 'JP-05', name: '秋田县' },
            { code: 'JP-18', name: '福井县' },
            { code: 'JP-42', name: '长崎县' },
            { code: 'JP-37', name: '香川县' },
            { code: 'JP-17', name: '石川县' },
            { code: 'JP-02', name: '青森县' },
            { code: 'JP-41', name: '佐贺县' },
            { code: 'JP-30', name: '和歌山县' },
            { code: 'JP-16', name: '富山县' },
            { code: 'JP-45', name: '宫崎县' }
        ]
    },
    
    // 韩国特别市/广域市数据
    korea: {
        cities: [
            { code: 'KR-11', name: '首尔特别市' },
            { code: 'KR-26', name: '釜山广域市' },
            { code: 'KR-27', name: '大邱广域市' },
            { code: 'KR-28', name: '仁川广域市' },
            { code: 'KR-29', name: '光州广域市' },
            { code: 'KR-30', name: '大田广域市' },
            { code: 'KR-31', name: '蔚山广域市' },
            { code: 'KR-50', name: '世宗特别自治市' },
            { code: 'KR-41', name: '京畿道' },
            { code: 'KR-42', name: '江原道' },
            { code: 'KR-43', name: '忠清北道' },
            { code: 'KR-44', name: '忠清南道' },
            { code: 'KR-45', name: '全罗北道' },
            { code: 'KR-46', name: '全罗南道' },
            { code: 'KR-47', name: '庆尚北道' },
            { code: 'KR-48', name: '庆尚南道' },
            { code: 'KR-49', name: '济州特别自治道' }
        ]
    },
    
    // 美国州数据
    usa: {
        states: [
            { code: 'US-AL', name: '阿拉巴马州' },
            { code: 'US-AK', name: '阿拉斯加州' },
            { code: 'US-AZ', name: '亚利桑那州' },
            { code: 'US-AR', name: '阿肯色州' },
            { code: 'US-CA', name: '加利福尼亚州' },
            { code: 'US-CO', name: '科罗拉多州' },
            { code: 'US-CT', name: '康涅狄格州' },
            { code: 'US-DE', name: '特拉华州' },
            { code: 'US-FL', name: '佛罗里达州' },
            { code: 'US-GA', name: '佐治亚州' },
            { code: 'US-HI', name: '夏威夷州' },
            { code: 'US-ID', name: '爱达荷州' },
            { code: 'US-IL', name: '伊利诺伊州' },
            { code: 'US-IN', name: '印第安纳州' },
            { code: 'US-IA', name: '爱荷华州' },
            { code: 'US-KS', name: '堪萨斯州' },
            { code: 'US-KY', name: '肯塔基州' },
            { code: 'US-LA', name: '路易斯安那州' },
            { code: 'US-ME', name: '缅因州' },
            { code: 'US-MD', name: '马里兰州' },
            { code: 'US-MA', name: '马萨诸塞州' },
            { code: 'US-MI', name: '密歇根州' },
            { code: 'US-MN', name: '明尼苏达州' },
            { code: 'US-MS', name: '密西西比州' },
            { code: 'US-MO', name: '密苏里州' },
            { code: 'US-MT', name: '蒙大拿州' },
            { code: 'US-NE', name: '内布拉斯加州' },
            { code: 'US-NV', name: '内华达州' },
            { code: 'US-NH', name: '新罕布什尔州' },
            { code: 'US-NJ', name: '新泽西州' },
            { code: 'US-NM', name: '新墨西哥州' },
            { code: 'US-NY', name: '纽约州' },
            { code: 'US-NC', name: '北卡罗来纳州' },
            { code: 'US-ND', name: '北达科他州' },
            { code: 'US-OH', name: '俄亥俄州' },
            { code: 'US-OK', name: '俄克拉荷马州' },
            { code: 'US-OR', name: '俄勒冈州' },
            { code: 'US-PA', name: '宾夕法尼亚州' },
            { code: 'US-RI', name: '罗得岛州' },
            { code: 'US-SC', name: '南卡罗来纳州' },
            { code: 'US-SD', name: '南达科他州' },
            { code: 'US-TN', name: '田纳西州' },
            { code: 'US-TX', name: '德克萨斯州' },
            { code: 'US-UT', name: '犹他州' },
            { code: 'US-VT', name: '佛蒙特州' },
            { code: 'US-VA', name: '弗吉尼亚州' },
            { code: 'US-WA', name: '华盛顿州' },
            { code: 'US-WV', name: '西弗吉尼亚州' },
            { code: 'US-WI', name: '威斯康星州' },
            { code: 'US-WY', name: '怀俄明州' }
        ]
    },
    
    // 琳凯蒂亚（田国）省市
    rincatia: {

        // 省份：具有奇幻魔法色彩
        provinces: [
            { code: 'RC-1', name: '华田都' },  // 参考物語中の星帝宮殿
            { code: 'RC-2', name: '望月省' },     // 参考物語中の双月の一つ
            { code: 'RC-3', name: '耀曦省' },     // 参考物語中の双月の一つ
            { code: 'RC-4', name: '星河省' },     // 参考物語中の星光河
            { code: 'RC-5', name: '铃兰省' },     // 参考物語中の銀色のベル铛木
            { code: 'RC-6', name: '彩虹省' },     // 参考物語中の虹彩要素
            { code: 'RC-7', name: '云霞省' },     // 参考物語中星帝宮殿の雲霞鳥飾装
            { code: 'RC-8', name: '蝶舞省' },     // 参考物語中の星蝶
            { code: 'RC-9', name: '蜜光省' }      // 参考物語中の蜂蜜色星光河
        ],
        // 市县：各県下轄の市町村
        cities: {
            'RC-1': [  // 星帝城下轄区域
                { code: 'RC-1-1', name: '星宮区' },
                { code: 'RC-1-2', name: '可儿区' },
                { code: 'RC-1-3', name: '法塔区' },
                { code: 'RC-1-4', name: '御圆区' },
                { code: 'RC-1-5', name: '月华区' },
                { code: 'RC-1-6', name: '星辉区' },
                { code: 'RC-1-7', name: '妙可市' },
                { code: 'RC-1-8', name: '青竹市' },
                { code: 'RC-1-9', name: '大田市' }
            ],
            'RC-2': [  // 銀月省下轄区域
                { code: 'RC-2-1', name: '霜华市' },
                { code: 'RC-2-2', name: '月影市' },
                { code: 'RC-2-3', name: '银辉州' }
            ],
            'RC-3': [  // 金月省下轄区域
                { code: 'RC-3-1', name: '金星市' },
                { code: 'RC-3-2', name: '日耀市' },
                { code: 'RC-3-3', name: '晨曦州' }
            ],
            'RC-4': [  // 星河省下轄区域
                { code: 'RC-4-1', name: '流光市' },
                { code: 'RC-4-2', name: '银河市' },
                { code: 'RC-4-3', name: '星光州' }
            ],
            'RC-5': [  // 铃兰省下轄区域
                { code: 'RC-5-1', name: '花语市' },
                { code: 'RC-5-2', name: '翠铃市' },
                { code: 'RC-5-3', name: '香谷州' }
            ],
            'RC-6': [  // 彩虹省下轄区域
                { code: 'RC-6-1', name: '虹光市' },
                { code: 'RC-6-2', name: '七色市' },
                { code: 'RC-6-3', name: '绚彩州' }
            ],
            'RC-7': [  // 雲霞省下轄区域
                { code: 'RC-7-1', name: '云海市' },
                { code: 'RC-7-2', name: '霞光市' },
                { code: 'RC-7-3', name: '天幕州' }
            ],
            'RC-8': [  // 蝶舞省下轄区域
                { code: 'RC-8-1', name: '翩跹市' },
                { code: 'RC-8-2', name: '羽舞市' },
                { code: 'RC-8-3', name: '幻蝶州' }
            ],
            'RC-9': [  // 蜜光省下轄区域
                { code: 'RC-9-1', name: '甘露市' },
                { code: 'RC-9-2', name: '蜜糖市' },
                { code: 'RC-9-3', name: '甜馨州' }
            ]
        }
    }
};

// LocationData加载模块
if (typeof module !== 'undefined' && module.exports) {
    module.exports = LocationData;
} else {
    window.LocationData = LocationData;
}
